version: '3.8'

services:
  iep-peerexplorer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iep-peerexplorer
    ports:
      - "4200:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    # For development with live reload
    # volumes:
    #   - ./dist/iep-peerexplorer:/usr/share/nginx/html
