server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # Load standard MIME types to ensure correct Content-Type for CSS, JS, etc.
    include /etc/nginx/mime.types;

    # Force all routes to load index.html for Angular routing
    location /peerexplorer {
        alias /usr/share/nginx/html;
        try_files $uri $uri/ /peerexplorer/index.html;

        # Cache static assets
        location ~* \.(jpg|jpeg|png|gif|ico|css|js)$ {
            expires 1y;
            add_header Cache-Control "public";
        }

        # Don't cache HTML
        location ~* \.html$ {
            expires -1;
            add_header Cache-Control "no-store";
        }
    }

}
