server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # Load standard MIME types to ensure correct Content-Type for CSS, JS, etc.
    include /etc/nginx/mime.types;

    # Force all routes to load index.html for Angular routing
    location /peerexplorer {
        alias /usr/share/nginx/html;
        try_files $uri $uri/ /peerexplorer/index.html;

        # Cache static assets
        location ~* \.(jpg|jpeg|png|gif|ico|css|js)$ {
            expires 1y;
            add_header Cache-Control "public";
        }

        # Don't cache HTML
        location ~* \.html$ {
            expires -1;
            add_header Cache-Control "no-store";
        }
    }

    # Proxy API requests to backend server
    location /api/ {
        proxy_pass https://iep-dev-devnet.decentage.io/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_cache_bypass $http_upgrade;
    }
}
